azs:
- name: z1
- name: z2
- name: z3

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 6

disk_types:
- disk_size: 10240
  name: 10GB

networks:
- name: default
  subnets:
  - azs: [z1, z2, z3]
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/20
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2 - 10.244.0.127
    - 10.244.1.0 - 10.244.1.127
    - 10.244.2.0 - 10.244.2.127
    - 10.244.3.0 - 10.244.3.127

vm_types:
- name: default
