name: etcd

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      api:
        client:
          tls: ((bosh_dns_client_tls))
        server:
          tls: ((bosh_dns_server_tls))
      aliases:
        etcd.default.etcd.bosh:
        - "*.etcd.default.etcd.bosh"

features:
  use_dns_addresses: true

instance_groups:
- name: etcd
  azs:
  - z1
  - z2
  - z3
  persistent_disk_type: 10GB
  instances: 3
  jobs:
  - name: bpm
    release: bpm
  - name: etcd
    release: etcd
    consumes:
      etcd_peers: {from: etcd_peers}
    provides:
      etcd_client: {as: etcd_client, shared: true}
    properties:
      tls:
        cert: ((etcd_client_tls.certificate))
        key: ((etcd_client_tls.private_key))
        trusted_ca: ((etcd_client_tls.ca))
        peer_cert: ((etcd_peer_tls.certificate))
        peer_key: ((etcd_peer_tls.private_key))
        peer_trusted_ca: ((etcd_peer_tls.ca))
  vm_type: default
  stemcell: default
  networks:
  - name: default

releases:
- name: bosh-dns
  sha1: 206805c1404b304b701a4e2aba8b7359fdf86047
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.1.0
  version: 1.1.0
- name: bpm
  version: latest
- name: etcd
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000

variables:
- name: client_ca
  type: certificate
  options:
    is_ca: true
    common_name: clientCA
- name: peer_ca
  type: certificate
  options:
    is_ca: true
    common_name: peerCA
- name: etcd_client_tls
  type: certificate
  options:
    ca: client_ca
    common_name: etcd.default.etcd.bosh
    extended_key_usage:
    - server_auth
    - client_auth
    alternative_names:
    - "etcd.default.etcd.bosh"
    - "*.etcd.default.etcd.bosh"
- name: etcd_peer_tls
  type: certificate
  options:
    ca: peer_ca
    common_name: etcd.default.etcd.bosh
    extended_key_usage:
    - server_auth
    - client_auth
    alternative_names:
    - "*.etcd.default.etcd.bosh"
- name: bosh_dns_ca
  type: certificate
  options:
    is_ca: true
    common_name: boshDNSCA
- name: bosh_dns_server_tls
  type: certificate
  options:
    ca: bosh_dns_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth
- name: bosh_dns_client_tls
  type: certificate
  options:
    ca: bosh_dns_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
